config/routes.rb
Rails.application.routes.draw do
  # Users
  devise_for :users
  resources :users

  # Wikis
  resources :wikis

  # Charges
  get 'charges/downgrade'
  resources :charges, only: [:new, :create]

  # Search
  get "search" => 'search#index', as: :search

  # Pages
  get 'pages/index'
  get 'pages/about'

  root to: 'pages#index'
 end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/search.rb
class Search
  def self.for(keyword)
    Wiki.eager_load(:collaborators).where("title LIKE ? AND private = ?", "%#{keyword}%", false) +
      User.where("name LIKE ?", "%#{keyword}%")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :collaborators
  has_many :wikis, :through => :collaborators

  validates_presence_of :name

  before_create :init

  def init
    self.role = 'standard'
  end

  def collaborator?(user, wiki)
    if Collaborator.where(user_id: user, wiki_id: wiki)
      true
    else
      false
    end
  end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, :through => :collaborators

  validates :title, presence: true
  validates :body, presence: true

  scope :visible_to, -> (user) { user ? all : where(private: false) }

  scope :recent, -> { order(created_at: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def after_sign_in_path_for(resource)
    wikis_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

  def user_not_authorized
    flash[:alert] = "You have to be signed in, have an account, or do not have permisson to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  
  def new
    @stripe_btn_data = {
       email: current_user.email,
       key: "#{ Rails.configuration.stripe[:publishable_key] }",
       description: "Blocipedia Upgrade",
       amount: Amount.default
    }
  end

  def create
    # Creates a Stripe Customer object, for associating
    # with the charge
    customer = Stripe::Customer.create(
     email: current_user.email, # params[:stripeEmail],
     card: params[:stripeToken]
    )

    # Where the real magic happens
    charge = Stripe::Charge.create(
     customer: customer.id, # Note -- this is NOT the user_id in your app
     amount: Amount.default,
     description: "Blocipedia Membership - #{current_user.email}",
     currency: 'usd'
    )

    flash[:notice] = "Thanks for upgrading, #{current_user.email}! You are now a premium member."
    current_user.role = "premium"
    current_user.save
    redirect_to wikis_path # or wherever
   
    # Stripe will send back CardErrors, with friendly messages
    # when something goes wrong.
    # This `rescue block` catches and displays those errors.
    rescue Stripe::CardError => e
     flash[:alert] = e.message
     redirect_to new_charge_path
  end

  def downgrade
    @user = current_user
    @user.role = "standard"
    if @user.save
      flash[:notice] = "You have successfully downgraded you account to standard."
      redirect_to wikis_path
    end
  end

end

class Amount 
  @@default = 200
  def self.default
    @@default
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

  def create
    
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if jump = find_jump_target
      redirect_to jump
    else
      session[:search_results] = request.url
      @results = Search.for(params[:keyword])
    end
  end

  private

  def find_jump_target
    Wiki.find_by(title: params[:keyword]) ||
      User.find_by(name: params[:keyword])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @wikis = Wiki.where(user_id: params[:id])
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    session.delete(:search_results)
    if params[:search] == nil
      @wikis = policy_scope(Wiki).recent
    else
      @wikis = Wiki.search(params[:search])
    end
    authorize @wikis
  end

  def show
    @wiki = Wiki.find(params[:id])
    @creator = User.find(@wiki.user_id)
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = Wiki.new(params.require(:wiki).permit(:title, :body, :private, :user_id))
    authorize @wiki
    @wiki.user_id = current_user.id
    if @wiki.save
      flash[:notice] = "Wiki was saved!"
      redirect_to wikis_path
    else
      flash[:alert] = "There was a error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.updated_by = current_user.id
    @wiki.update_attributes(params.require(:wiki).permit(:title, :body, :private, :updated_by, :user_id, :user_ids, :user_ids => []))
    if @wiki.save
      flash[:notice] = "Wiki was updated!"
      redirect_to @wiki
    else
      flash[:alert] = "There was a error saving the wiki. Please try again."
      render :new
    end
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

def markdown_to_html(markdown)
  renderer = Redcarpet::Render::HTML.new
  extensions = {fenced_code_blocks: true}
  redcarpet = Redcarpet::Markdown.new(renderer, extensions)
  (redcarpet.render markdown).html_safe
end

end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert-error-block">
      <div class="header">Oh snap! Something went wrong!</div>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wikis_helper.rb
module WikisHelper

  def author(wiki, creator)
    if current_user.nil?
      @author = creator.name
    else
      if wiki.user_id == current_user.id
        @author = 'This bliki is yours.'
      else
        @author = 'This bliki was created by ' + creator.name + '.'
      end
    end
    return @author
  end

  def status(wiki)
    if wiki.private == true
      @status = 'This bliki is private.'
    else
      @status = 'This bliki is public.'
    end
    return @status
  end

  def get_user_name(id)
    if id == nil
      return "No updates yet"
    end
    @user = User.find(id)
    return @user.name
  end

  def get_collaborator_id(id)
    if id == nil
      return "No updates yet"
    end
    @user = User.find(id)
    return @user.id
  end

end

app/views/charges/new.html.erb
<h2 class="page-header">
  <div class="container">Upgrade to Premium
    <% if current_user %>
      <%= form_tag charges_path do %>
        <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
      <% end %>
    <% end %>
  </div>
</h2>
<div class="container">
  <div id="prem-plan">
    <ul>
      <li><h1 class="title">This is what you get!</h1></li>
      <li>Cost = <span class="strong">$2</span> a month</li>
      <li>Unlimited <span class="strong">PUBLIC</span> Wikis</li>
      <li>Unlimited <span class="strong">PRIVATE</span> Wikis</li>
      <li>Unlimited <span class="strong">High</span> Fives</li>
      <li>1-year <span class="strong">FREE</span> Pancakes</li>
      <li>And... <span class="strong"> a heck yeah!</span></li>
    </ul>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer row">
  <ul>
    <li>About</li>
    <li>Blog</li>
    <li>Contact</li>
    <li>Jobs</li>
    <li>Terms</li>
    <li>Privacy</li>
  </ul>
  <div class="devops">
    <small> Created on </small>
    <%= image_tag("thefly.png") %>
  </div>

</footer>

app/views/layouts/_nav.html.erb
<!-- _nav partial -->
<header class="nav row">
  <div class="container">
    <%= link_to root_path do %>
      <%= image_tag("logo.png", :alt => "Bliki") %>
    <% end %>
    <ul>
      <li><%= link_to "Blikis", wikis_path %></li>
    <% if current_user.present? %>
      <li>
        <%= link_to current_user.name, user_path(current_user.id) %>
      </li>
      <% if current_user.role == "admin" %>
      <li>
          Admin
      </li>
      <% end %>
      <% if current_user.role == "standard" %>
      <li>
          <%= link_to "Upgrade", new_charge_path %>
      </li>
      <% end %>
      <% if current_user.role == "premium" %>
      <li>
          <%= link_to "Downgrade", charges_downgrade_path %>
      </li>
      <% end %>
      <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
    <% else %>
      <li><%= link_to "Sign In", new_user_session_path %></li>
      <li><%= link_to "Sign Up", new_user_registration_path, class: "highlight" %></li>
    <% end %>
    </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blikipedia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <a href="#" data-dismiss="alert" class="close">×</a>
        <ul>
          <li>
            <%= value %>
          </li>
        </ul>
    </div>
  <% end %>
  <%= render 'layouts/nav' %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/index.html.erb
<div class="hero row">
  <div class="container">
    <h1>Knowledge by the people, for the people.</h1>
    <div class="call-to-action">
      <%= link_to "Get Started", new_user_registration_path, :class=>'btn hero' %>
    </div>
  </div>
</div>
<div class="devices row">
  <div class="container">
   <%= image_tag("devices.png", :class=>"device-image") %>
  </div>
</div>
<div class="learn row">
  <%= link_to new_user_registration_path do %>
    <h1 class="free">Be Free!</h1>
    <h3><span class="bold free">FREE!</span> <span class="kern-minus-3">Unlimited Public Blikis</span></h3>
    <h3><span class="bold free">FREE!</span> <span class="kern-minus-3">Contribute to Public Blikis</span></h3>
  <% end %>
</div>

app/views/search/index.html.erb
<h2 class="page-header">
  <div class="container">Search Results
    <% if current_user %>
      <%= link_to "New", new_wiki_path, class: 'btn normal green right', id: 'new_bliki' %>
    <% end %>
  </div>
</h2>
<div class="results container">
  <ul>
    <% if @results.blank? %>

      <li><i>No Results</i></li>

    <% else %>
      <% @results.each do |result| %>

        <li>
          <% if result.try(:title) %>
            <%= link_to result.title, wiki_path(result.id) %> <em class="badge">bliki</em>
          <% elsif result.try(:name) %>
            <%= link_to result.name, user_path(result.id) %>&nbsp;<em class="badge">user</em>
          <% end %>
        </li>

      <% end %>
    <% end %>
  </ul>
</div>

app/views/users/show.html.erb
<h2 class="page-header">
  <div class="container"><%= @user.name %>
    <% if current_user %>
      <%= link_to "New", new_wiki_path, class: 'btn normal green right', id: 'new_bliki' %>
    <% end %>
  </div>
</h2>


<div class="container user-profile">
<h1>Author of</h1>
<% @wikis.each do |w| %>
  <div><%= link_to w.title, wiki_path(w.id), class: 'title' %> </div>
<% end %>

<h1>Collaborator on</h1>
<% @user.wikis.each do |w| %>
  <div class="title"><%= link_to w.title, wiki_path(w.id), class: 'title' %> </div>
<% end %>
</div>

app/views/wikis/_form.html.erb
<%= simple_form_for @wiki, input_html: { class: 'form' } do |f| %>
  <div class="field block">
    <%= f.input :title, placeholder: "Enter your bliki title", label: false %>
  </div>
   <div class="field block">
    <%= f.input :body, as: :text, placeholder: "Enter your bliki content here", label: false, input_html:{ rows: 8 } %>
  </div>
  <% if current_user.role == 'admin' || current_user.role == 'premium' %>
    <div class="checkbox">
      <%= f.check_box :private %>
      <%= f.label "Is this Wiki private?" %>
    </div>
    <div class="collabos">
      Select collaborators (optional)
      <%= f.association :users %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit "Save it to kick the knowledge!", class: "btn block orange" %>
  </div>
<% end %>

app/views/wikis/_help.html.erb
<div class="help" style="display: none;">
  <h1> Markdown Cheat Sheet</h1>
  <div class="headers">
    <h4>Headers</h4>
    <p># H1 <br/></p>
    <p>## H2 <br/></p>
    <p>### H3 <br/></p>
    <p>#### H4 <br/></p>
    <p>##### H5 <br/></p>
    <p>###### H6<br/></p>
  </div>
  <div class="emphasis">
    <h4>Emphasis</h4>
    <p>
      Emphasis, aka italics, with *asterisks* or _underscores_.<br/>

      Strong emphasis, aka bold, with **asterisks** or __underscores__.<br/>

      Combined emphasis with **asterisks and _underscores_**.<br/>
    </p>
  </div>
  <div class="links">
    <h4>Links</h4>
    <p>
      [I'm an inline-style link](https://www.google.com)<br/>

      [I'm an inline-style link with title](https://www.google.com "Google's Homepage")<br/>

      [I'm a reference-style link][Arbitrary case-insensitive reference text]<br/>

      [I'm a relative reference to a repository file](../blob/master/LICENSE)<br/>

      [You can use numbers for reference-style link definitions][1]<br/>

      Or leave it empty and use the [link text itself]<br/>

      Some text to show that the reference links can follow later.<br/>

      [arbitrary case-insensitive reference text]: https://www.mozilla.org<br/>
      [1]: http://slashdot.org<br/>
      [link text itself]: http://www.reddit.com<br/>
    </p>
  </div>
  <div class="code">
    <h4>Code</h4>
    <p>
      <p>Inline `code` has `back-ticks around` it.</p><br/>
      <p>Blocks of code are either fenced by lines with three back-ticks ```, or are indented with four spaces.<br/>
     ```javascript<br/>
     var s = "JavaScript syntax highlighting";<br/>
     alert(s);<br/>
     ```<br/>
   </p>
    </p>
  </div>
  <div class="blockquote">
    <h4>Blockquotes</h4>
    <p>
      > Blockquotes are very handy in email to emulate reply text.<br/>
      > This line is part of the same quote.<br/>
    </p>
  </div>
</div>

app/views/wikis/edit.html.erb
<div class="bliki">
  <h1>Need to change it up?</h1>
  <button class="help-toggle">Need some markdown help? Click here.</button>
  <%= render partial: 'help' %>
  <%= render partial: 'form', locals: { topic: @wiki } %>
</div>

app/views/wikis/index.html.erb
<h2 class="page-header">
  <div class="container">Blikis
    <% if current_user %>
      <%= link_to "New", new_wiki_path, class: 'btn normal green right', id: 'new_bliki' %>
    <% end %>
  </div>
</h2>
<div class='search-box container'>
  <%= form_tag search_path, method: :get do %>
    <%= text_field_tag 'keyword', nil, placeholder: 'Search by title or author name' %>
  <% end %>
</div>
<div class="container">
<% if @wikis.nil? %>
  <h1> No blikis found. </h1>
<% else %>
  <% @wikis.each do | wiki | %>
    <%= link_to wiki_path(wiki)  do %>
      <div class="wiki wiki-item row">
        <h2 class="title"><%= wiki.title %></h2>
        <div class="footer">
          <div class="author">
            <div class="owner">by <%= link_to wiki.user.name, user_path(wiki.user.id), class: "name" %> on <%= wiki.created_at.strftime("%-m/%-d/%Y") %></div>
          </div>
          <div class="author">
            <div class="owner"> &nbsp;&nbsp;&nbsp;Last updated by <%= link_to get_user_name(wiki.updated_by), user_path(get_collaborator_id(wiki.updated_by), class: "name") %></a></div>
          </div>
          <div class="stats">
            <span class="reads">
              <%= rand(10) %>K reads
            </span>
            <span class="status">
              <% if wiki.private == true %>
                <em class="badge orange">private</em>
              <% else %>
                <em class="badge green">public</em>
              <% end %>
            </span>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>
</div>

app/views/wikis/new.html.erb
<div class="bliki">
  <h1>Ready to drop some knowledge?</h1>
  <button class="help-toggle">Need some markdown help? Click here.</button>
  <%= render partial: 'help' %>
  <%= render partial: 'form', locals: { topic: @wiki } %>
</div>

app/views/wikis/show.html.erb
<div class="container row">

  <div class="wiki">
    <header class="heading">

      <% if session[:search_results] %>
        <%= link_to 'Back to search results', session[:search_results] %>
      <% else %>
        <%= link_to "Back", wikis_path %>
      <% end %>

      <div class="status">
        by <%= author(@wiki, @creator) %>.
        <%= status(@wiki) %>
      </div>
    </header>

    <h1 class="title"><%= @wiki.title %></h1>

    <article class= "markdown-body">
      <%= markdown_to_html @wiki.body %>
    </article>
  </div>

  <% if @wiki.private == true %>
    <div class="collaborators">
      <h1>Collaborators</h1>
      <% @wiki.users.each do |user| %>
        <% if user.id == current_user.id %>
          <div class="user-details green"><%= link_to user.name, user_path(user.id), class: "green" %></div>
        <% else %>
          <div class="user-details"><%= link_to user.name, user_path(user.id) %></div>
        <% end %>
      <% end %>
    </div>
  <% end %>

  <% if current_user.present? %>
    <% if current_user.collaborator?(current_user.id, @wiki.id) || current_user.id == @wiki.user_id %>
      <div class="actions">
        <%= link_to "Edit this Bliki", edit_wiki_path(@wiki), class: 'btn blue' %>
      </div>
    <% end %>
  <% end %>

</div>